### ISSUE TITLE
[typescript] parse return type incorrect

### ISSUE THREAD

**Issue by bgoyarts** [Inist-CNRS/node-csv-string#40]
The return-type of parse seems incorrect. 

The types are defined as follows: 

```typescript
  type rowElement = string | number | boolean;
  type row = rowElement[];

  function parse(input: string, separator?: separator, quote?: string): row;
```

However, parse returns an array of `rows`. 

Currently I'm getting errors because I try to do the following : 

```typescript
    const header = parse(data)[0] 
```
If I `console.log(header)` I have received an array of strings. However header is now implicitly typed as `rowElement` which means typescript sees it as a `string | number | boolean`

You can check out an example [here](https://codesandbox.io/s/objective-hamilton-i6rok?file=/src/index.ts)

**Comment by touv** [comment]
Do you have the same error with the new version 4.0.1
