### ISSUE TITLE
Missing dist folder and dist/index.js in v4.0.0

### ISSUE THREAD

**Issue by mishijima** [Inist-CNRS/node-csv-string#42]
Hello,

First of all, it's a nice library and thank you all for that.

I upgraded from v3.2.0 to v4.0.0 last night and encountered an issue when I run my app.

```
(node:19543) UnhandledPromiseRejectionWarning: Error: Cannot find module 
'./node_modules/csv-string/dist/index.js'. Please verify that the package.json
has a valid "main" entry
```

The node_modules/csv-string has the following files
- LICENSE
- package.json
- README.md

All I did was running 'npm install csv-string', did I miss a step or two?

Thank you in advance.

**Comment by Ephigenia** [comment]
I also encountered that issue and can confirm that issue in the latest 4.0.0 release.

**Comment by touv** [comment]
See the patch : https://github.com/Inist-CNRS/node-csv-string/blob/master/package.json#L61  

now you can use safely the new release 4.0.1

**Comment by Ephigenia** [comment]
Just tested the new release 4.0.1 and works again. Thanks for fixing.

**Comment by mishijima** [comment]
Hello,

I've just tested 4.0.1 and it worked. Thank you everyone!
